server:
  port: 8078
spring:
  application:
    name: eureka-consumer

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 #default 30 seconds
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
