server:
  port: 8068

spring:
  application:
    name: eureka-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lonyee1989/lemon-cloud-config.git
        encrypt:
          enabled: true