server:
  port: 8068

spring:
  application:
    name: eureka-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lonyee1989/lemon-cloud-config.git
         # username: user
         # password: secret
          searchPaths: dev  #利用查询地址区分不同配置环境
        encrypt:
          enabled: true