server:
  port: 8090
spring:
  application:
    name: eureka-gateway

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 #default 30 seconds
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/

zuul:
  routes:
    account:
      path: /account/**
      serviceId: account-service
    finance:
      path: /finance/**
      serviceId: finance-service
    security:
      path: /security/**
      serviceId: security-service
    gateway-a:
      path: /gateway-a/**
      serviceId: eureka-service
